services:
    php:
        container_name: php_fpm
        build:
            context: "./docker/php"
        volumes:
            - "./:/usr/share/nginx/html"
        networks:
            - lemp
        depends_on:
            - "db"

    web:
        container_name: nginx_server
        build:
            context: "./docker/nginx"
        ports:
            - "8080:80"
        volumes:
            - "./:/usr/share/nginx/html"
            - "./conf:/etc/nginx/conf.d"
        links:
            - php
        networks:
            - lemp

    redis:
        container_name: redis_server
        image: redis:latest
        links:
            - php
        networks:
            - lemp
        ports:
            - "6379:6379"

    db:
        container_name: mariadb_server
        image: mariadb
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
        volumes:
            - "./db:/var/lib/mysql"
        networks:
            - lemp

    adminer:
        container_name: adminer_server
        image: adminer
        restart: always
        ports:
            - 5555:8080
        networks:
            - lemp

networks:
    lemp:
        driver: bridge
